apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cmp-mcp-server
  labels:
    app: cmp-mcp-server
spec:
  to:
    kind: Service
    name: cmp-mcp-server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
